In [31]:
import pandas as pd
import numpy as np

p = pd.read_csv('DelayedFlights.csv')
print(p.head(5))

df = p[["DepTime", "CRSDepTime", "ArrTime", "CRSArrTime", "ArrDelay", "UniqueCarrier", "FlightNum", "Origin", "Dest", "DepDelay", "Distance", "Cancelled"]]
df

   Unnamed: 0  Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  \
0           0  2008      1           3          4   2003.0        1955
1           1  2008      1           3          4    754.0         735
2           2  2008      1           3          4    628.0         620
3           4  2008      1           3          4   1829.0        1755
4           5  2008      1           3          4   1940.0        1915

   ArrTime  CRSArrTime UniqueCarrier  ...  TaxiIn TaxiOut  Cancelled  \
0   2211.0        2225            WN  ...     4.0     8.0          0
1   1002.0        1000            WN  ...     5.0    10.0          0
2    804.0         750            WN  ...     3.0    17.0          0
3   1959.0        1925            WN  ...     3.0    10.0          0
4   2121.0        2110            WN  ...     4.0    10.0          0

   CancellationCode  Diverted  CarrierDelay  WeatherDelay NASDelay  \
0                 N         0           NaN           NaN      NaN
1                 N         0           NaN           NaN      NaN
2                 N         0           NaN           NaN      NaN
3                 N         0           2.0           0.0      0.0
4                 N         0           NaN           NaN      NaN

  SecurityDelay  LateAircraftDelay
0           NaN                NaN
1           NaN                NaN
2           NaN                NaN
3           0.0               32.0
4           NaN                NaN

[5 rows x 30 columns]

,DepTime,CRSDepTime,ArrTime,CRSArrTime,ArrDelay,UniqueCarrier,FlightNum,Origin,Dest,DepDelay,Distance,Cancelled
0,2003.0,1955,2211.0,2225,-14.0,WN,335,IAD,TPA,8.0,810,0
1,754.0,735,1002.0,1000,2.0,WN,3231,IAD,TPA,19.0,810,0
2,628.0,620,804.0,750,14.0,WN,448,IND,BWI,8.0,515,0
3,1829.0,1755,1959.0,1925,34.0,WN,3920,IND,BWI,34.0,515,0
4,1940.0,1915,2121.0,2110,11.0,WN,378,IND,JAX,25.0,688,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1936753,1250.0,1220,1617.0,1552,25.0,DL,1621,MSP,ATL,30.0,906,0
1936754,657.0,600,904.0,749,75.0,DL,1631,RIC,ATL,57.0,481,0
1936755,1007.0,847,1149.0,1010,99.0,DL,1631,ATL,IAH,80.0,689,0
1936756,1251.0,1240,1446.0,1437,9.0,DL,1639,IAD,ATL,11.0,533,0
1936757,1110.0,1103,1413.0,1418,-5.0,DL,1641,SAT,ATL,7.0,874,0

In [33]:
print("Resumen estadÃ­stic")
print(df.describe())
print()

for column in df:
    if df[column].isnull().values.any():
        print ("la columna", column, "tÃ© dades que falten")
print()

print("Velocitat mitjana del trajecte")
df["velocitat"] = df["Distance"] / (df["CRSArrTime"] - df["CRSDepTime"])
print(df["velocitat"])
print()

print("Itinerari")
df["Ori_Dest"] = df["Origin"] + "-" + df["Dest"]
print(df["Ori_Dest"])
print()

aeroliretrasos = df.groupby("UniqueCarrier")["ArrDelay"].sum().sort_values(ascending=False)
print("Llista de les 10 aerolÃ­nies amb mÃ©s retrÃ s acumulat (en minuts)")
print(aeroliretrasos.head(10))
print()
print()

df.set_index("Ori_Dest")
velocitatsmitjanas = df.groupby("Ori_Dest")["velocitat"].mean()
print("Les velocitats mitjanas dels trajectes en miles/min sÃ³n")
print(velocitatsmitjanas)
print()

print("Els trajectes mÃ©s llargs sÃ³n")
print(df.groupby("Ori_Dest")["Distance"].mean().sort_values(ascending=False).head(10))
print()

df.reset_index()

Resumen estadÃ­stic
            DepTime    CRSDepTime       ArrTime    CRSArrTime      ArrDelay  \
count  1.936758e+06  1.936758e+06  1.929648e+06  1.936758e+06  1.928371e+06
mean   1.518534e+03  1.467473e+03  1.610141e+03  1.634225e+03  4.219988e+01
std    4.504853e+02  4.247668e+02  5.481781e+02  4.646347e+02  5.678472e+01
min    1.000000e+00  0.000000e+00  1.000000e+00  0.000000e+00 -1.090000e+02
25%    1.203000e+03  1.135000e+03  1.316000e+03  1.325000e+03  9.000000e+00
50%    1.545000e+03  1.510000e+03  1.715000e+03  1.705000e+03  2.400000e+01
75%    1.900000e+03  1.815000e+03  2.030000e+03  2.014000e+03  5.600000e+01
max    2.400000e+03  2.359000e+03  2.400000e+03  2.400000e+03  2.461000e+03

          FlightNum      DepDelay      Distance     Cancelled     velocitat
count  1.936758e+06  1.936758e+06  1.936758e+06  1.936758e+06  1.936758e+06
mean   2.184263e+03  4.318518e+01  7.656862e+02  3.268348e-04           inf
std    1.944702e+03  5.340250e+01  5.744797e+02  1.807562e-02           NaN
min    1.000000e+00  6.000000e+00  1.100000e+01  0.000000e+00 -2.380000e+02
25%    6.100000e+02  1.200000e+01  3.380000e+02  0.000000e+00  2.280000e+00
50%    1.543000e+03  2.400000e+01  6.060000e+02  0.000000e+00  2.930435e+00
75%    3.422000e+03  5.300000e+01  9.980000e+02  0.000000e+00  3.953052e+00
max    9.742000e+03  2.467000e+03  4.962000e+03  1.000000e+00           inf

la columna ArrTime tÃ© dades que falten
la columna ArrDelay tÃ© dades que falten

Velocitat mitjana del trajecte
0          3.000000
1          3.056604
2          3.961538
3          3.029412
4          3.528205
             ...
1936753    2.728916
1936754    3.228188
1936755    4.226994
1936756    2.705584
1936757    2.774603
Name: velocitat, Length: 1936758, dtype: float64

Itinerari

C:\Users\Ripley\AppData\Local\Temp\ipykernel_3560\1736093681.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["velocitat"] = df["Distance"] / (df["CRSArrTime"] - df["CRSDepTime"])
C:\Users\Ripley\AppData\Local\Temp\ipykernel_3560\1736093681.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Ori_Dest"] = df["Origin"] + "-" + df["Dest"]

0          IAD-TPA
1          IAD-TPA
2          IND-BWI
3          IND-BWI
4          IND-JAX
            ...
1936753    MSP-ATL
1936754    RIC-ATL
1936755    ATL-IAH
1936756    IAD-ATL
1936757    SAT-ATL
Name: Ori_Dest, Length: 1936758, dtype: object

Llista de les 10 aerolÃ­nies amb mÃ©s retrÃ s acumulat (en minuts)
UniqueCarrier
WN    11319092.0
AA     8889066.0
UA     6733013.0
MQ     6396704.0
OO     5978936.0
XE     5176042.0
DL     4535644.0
CO     4045932.0
EV     3888131.0
YV     3691461.0
Name: ArrDelay, dtype: float64


Les velocitats mitjanas dels trajectes en miles/min sÃ³n
Ori_Dest
ABE-ATL    3.224047
ABE-BHM    6.092308
ABE-CLE    2.768967
ABE-CLT    2.835365
ABE-CVG    3.337387
             ...
YUM-IPL   -0.529457
YUM-LAS    2.365037
YUM-LAX    4.995543
YUM-PHX    1.625508
YUM-SLC    2.587264
Name: velocitat, Length: 5205, dtype: float64

Els trajectes mÃ©s llargs sÃ³n
Ori_Dest
HNL-EWR    4962.0
EWR-HNL    4962.0
HNL-ATL    4502.0
ATL-HNL    4502.0
ORD-HNL    4243.0
HNL-ORD    4243.0
KOA-ORD    4213.0
ORD-OGG    4184.0
HNL-MSP    3972.0
MSP-HNL    3972.0
Name: Distance, dtype: float64

,index,DepTime,CRSDepTime,ArrTime,CRSArrTime,ArrDelay,UniqueCarrier,FlightNum,Origin,Dest,DepDelay,Distance,Cancelled,velocitat,Ori_Dest
0,0,2003.0,1955,2211.0,2225,-14.0,WN,335,IAD,TPA,8.0,810,0,3.000000,IAD-TPA
1,1,754.0,735,1002.0,1000,2.0,WN,3231,IAD,TPA,19.0,810,0,3.056604,IAD-TPA
2,2,628.0,620,804.0,750,14.0,WN,448,IND,BWI,8.0,515,0,3.961538,IND-BWI
3,3,1829.0,1755,1959.0,1925,34.0,WN,3920,IND,BWI,34.0,515,0,3.029412,IND-BWI
4,4,1940.0,1915,2121.0,2110,11.0,WN,378,IND,JAX,25.0,688,0,3.528205,IND-JAX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1936753,1936753,1250.0,1220,1617.0,1552,25.0,DL,1621,MSP,ATL,30.0,906,0,2.728916,MSP-ATL
1936754,1936754,657.0,600,904.0,749,75.0,DL,1631,RIC,ATL,57.0,481,0,3.228188,RIC-ATL
1936755,1936755,1007.0,847,1149.0,1010,99.0,DL,1631,ATL,IAH,80.0,689,0,4.226994,ATL-IAH
1936756,1936756,1251.0,1240,1446.0,1437,9.0,DL,1639,IAD,ATL,11.0,533,0,2.705584,IAD-ATL
1936757,1936757,1110.0,1103,1413.0,1418,-5.0,DL,1641,SAT,ATL,7.0,874,0,2.774603,SAT-ATL

In [34]:
df.to_csv("noudelayedfligths.csv", index=False)

# IntegraciÃ³ de figures creades per Matplotlib


<img src="categorica.png">

<img src="numerica.png">

<img src="numcategorica.png">

<img src="correlacio.png">

<img src="2series.png">

<img src="3variables.png">